version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kanban_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: kanban
    ports:
      - "5433:5432"  # <-- ИСПРАВЛЕНО: на твоем компьютере порт будет 5433, а внутри контейнера останется стандартный 5432
    volumes:
      - kanban_pgdata:/var/lib/postgresql/data
    networks:
      - kanban_network

  app:
    build:
      context: ./backend_aliya
      dockerfile: Dockerfile
    container_name: kanban_backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=5432  # Когда бэкенд и БД внутри докера в одной сети, они общаются по внутреннему порту (5432), тут оставляем так
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_NAME=kanban
    depends_on:
      - db
    networks:
      - kanban_network

volumes:
  kanban_pgdata:
    external: true

networks:
  kanban_network:
    driver: bridge
